name: clang-format

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches-ignore:
      - main
jobs:
  format:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          clang-format -i $(git ls-files '*.cpp' '*.hpp' '*.h' '*.c')

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
